spring:
  application:
    name: RATING-SERVICE
  datasource:
    url: jdbc:mysql://mysql-user:3306/microservices
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8083

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://registry:8761/eureka
  instance:
    prefer-ip-address: true

okta:
  oauth2:
    issuer: https://dev-77584981.okta.com/oauth2/default
    audience: api://default
